package attendancemonitoring;

import fpregistration.*;

//import com.sun.speech.freetts.Voice;
//import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
// import java.util.GregorianCalendar;
// import java.util.HashMap;
import javax.sound.sampled.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
// import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benoe
 */
public class MainGUI extends javax.swing.JFrame {
    //private String[] keys;
    //private int currentIndex;
    // private Timer timer;
    //static DefaultTableModel mtblCalendar = new DefaultTableModel(){
    // public boolean isCellEditable(int rowIndex, int mColIndex){return false;}}; //Table model
    
    static int realYear, realMonth, realDay, currentYear, currentMonth;
    public static int timeType = 0;
    public static volatile boolean isScanningAttendance = true;
    //public static DefaultListModel model = new DefaultListModel();
    //Crud myCrud = new Crud();
    DigitalPersona dp = new DigitalPersona();
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
//        popUp(System.getProperty("user.dir"),"DIR");
        initComponents();
        setClockTime s = new setClockTime();
        setCalendar();
        lblCompanyName.setText(Config.COMPANY_NAME);
        lblSystemName.setText("Attendance Monitoring System ("+Config.MACHINE_ID+")");
        UIManager.put("OptionPane.background", Color.WHITE);
        UIManager.put("Panel.background", Color.WHITE);
        UIManager.put("OptionPane.messagebackground", Color.WHITE);
        
        try {
            
            ButtonImageIcon.fitImageToButton(btnHelp, System.getProperty("user.dir")+"\\img\\help.png", WIDTH);
            ButtonImageIcon.fitImageToButton(btnInfo, System.getProperty("user.dir")+"\\img\\info.png", WIDTH);
            ButtonImageIcon.fitImageToButton(btnContact, System.getProperty("user.dir")+"\\img\\fp0.png", WIDTH);
            ButtonImageIcon.fitImageToButton(cmdClear, System.getProperty("user.dir")+"\\img\\cancel.png", WIDTH);
            ButtonImageIcon.stretchImageToButton(btnBanner, System.getProperty("user.dir")+"\\img\\banner.jpg", 0);
           
        } catch (IOException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelCompanyName = new javax.swing.JPanel();
        jPanelBanner = new javax.swing.JPanel();
        btnBanner = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lblCompanyName = new javax.swing.JLabel();
        lblSystemName = new javax.swing.JLabel();
        jPanelDateTimeDisplay = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        jPanelTimeInTimeOutButtons = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmdTimeIn = new javax.swing.JButton();
        cmdTimeOut = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jPanelSettings = new javax.swing.JPanel();
        btnHelp = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnContact = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblAttendanceCardTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblEmpID1 = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        lblEmpName1 = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblDivision1 = new javax.swing.JLabel();
        lblDivision = new javax.swing.JLabel();
        lblSection1 = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblAMin1 = new javax.swing.JLabel();
        lblAMin = new javax.swing.JLabel();
        lblAMout1 = new javax.swing.JLabel();
        lblAMout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblPMin1 = new javax.swing.JLabel();
        lblPMin = new javax.swing.JLabel();
        lblPMout1 = new javax.swing.JLabel();
        lblPMout = new javax.swing.JLabel();

        jFrame1.setExtendedState(JFrame.MAXIMIZED_BOTH);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtP.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gear.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary Bee Tech Solutions - Attendance System");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(jFrame1.getExtendedState());
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        jPanelCompanyName.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCompanyName.setMaximumSize(new java.awt.Dimension(1200, 1000));
        jPanelCompanyName.setMinimumSize(new java.awt.Dimension(1200, 1000));
        jPanelCompanyName.setName(""); // NOI18N
        jPanelCompanyName.setPreferredSize(new java.awt.Dimension(1200, 1000));
        jPanelCompanyName.setLayout(new java.awt.GridLayout(1, 2));

        jPanelBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBanner.setMaximumSize(new java.awt.Dimension(1200, 500));
        jPanelBanner.setMinimumSize(new java.awt.Dimension(1200, 500));
        jPanelBanner.setPreferredSize(new java.awt.Dimension(1200, 500));
        jPanelBanner.setLayout(new java.awt.GridLayout(1, 1));

        btnBanner.setBackground(new java.awt.Color(255, 255, 255));
        btnBanner.setBorder(null);
        btnBanner.setMaximumSize(new java.awt.Dimension(600, 150));
        btnBanner.setMinimumSize(new java.awt.Dimension(600, 150));
        btnBanner.setPreferredSize(new java.awt.Dimension(600, 150));
        jPanelBanner.add(btnBanner);

        jPanelCompanyName.add(jPanelBanner);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(2, 1));

        lblCompanyName.setBackground(new java.awt.Color(0, 0, 204));
        lblCompanyName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyName.setText("<<TEXT HERE>>");
        lblCompanyName.setToolTipText("");
        lblCompanyName.setMaximumSize(new java.awt.Dimension(50, 50));
        lblCompanyName.setMinimumSize(new java.awt.Dimension(50, 50));
        lblCompanyName.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(lblCompanyName);

        lblSystemName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSystemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemName.setText("ATTENDANCE MONITORING SYSTEM");
        lblSystemName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSystemName.setMaximumSize(new java.awt.Dimension(50, 50));
        lblSystemName.setMinimumSize(new java.awt.Dimension(50, 50));
        lblSystemName.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(lblSystemName);

        jPanelCompanyName.add(jPanel8);

        getContentPane().add(jPanelCompanyName);

        jPanelDateTimeDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDateTimeDisplay.setMaximumSize(new java.awt.Dimension(174, 400));
        jPanelDateTimeDisplay.setMinimumSize(new java.awt.Dimension(174, 400));
        jPanelDateTimeDisplay.setPreferredSize(new java.awt.Dimension(174, 400));
        jPanelDateTimeDisplay.setLayout(new java.awt.GridLayout(2, 1, 0, 2));

        lblTime.setBackground(new java.awt.Color(0, 0, 0));
        lblTime.setFont(new java.awt.Font("Digital-7 Mono", 0, 92)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 204, 0));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("time");
        lblTime.setToolTipText("");
        lblTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTime.setMaximumSize(new java.awt.Dimension(174, 300));
        lblTime.setMinimumSize(new java.awt.Dimension(174, 300));
        lblTime.setOpaque(true);
        lblTime.setPreferredSize(new java.awt.Dimension(174, 300));
        jPanelDateTimeDisplay.add(lblTime);

        lblDay.setBackground(new java.awt.Color(204, 204, 204));
        lblDay.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("day");
        lblDay.setToolTipText("");
        jPanelDateTimeDisplay.add(lblDay);

        getContentPane().add(jPanelDateTimeDisplay);

        jPanelTimeInTimeOutButtons.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTimeInTimeOutButtons.setLayout(new java.awt.GridLayout(1, 4));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(300, 273));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 273));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );

        jPanelTimeInTimeOutButtons.add(jPanel5);

        cmdTimeIn.setBackground(Color.GREEN);
        cmdTimeIn.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        cmdTimeIn.setForeground(new java.awt.Color(255, 255, 255));
        cmdTimeIn.setText("Time In");
        cmdTimeIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdTimeIn.setMaximumSize(new java.awt.Dimension(350, 150));
        cmdTimeIn.setMinimumSize(new java.awt.Dimension(350, 150));
        cmdTimeIn.setPreferredSize(new java.awt.Dimension(350, 150));
        cmdTimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimeInActionPerformed(evt);
            }
        });
        jPanelTimeInTimeOutButtons.add(cmdTimeIn);

        cmdTimeOut.setBackground(Color.lightGray);
        cmdTimeOut.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        cmdTimeOut.setForeground(new java.awt.Color(255, 255, 255));
        cmdTimeOut.setText("Time Out");
        cmdTimeOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdTimeOut.setMaximumSize(new java.awt.Dimension(350, 150));
        cmdTimeOut.setMinimumSize(new java.awt.Dimension(350, 150));
        cmdTimeOut.setPreferredSize(new java.awt.Dimension(350, 150));
        cmdTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimeOutActionPerformed(evt);
            }
        });
        jPanelTimeInTimeOutButtons.add(cmdTimeOut);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(300, 273));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 273));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );

        jPanelTimeInTimeOutButtons.add(jPanel6);

        getContentPane().add(jPanelTimeInTimeOutButtons);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(new java.awt.GridLayout(2, 1));

        jPanelSettings.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelSettings.setMinimumSize(new java.awt.Dimension(120, 20));
        jPanelSettings.setPreferredSize(new java.awt.Dimension(120, 20));
        jPanelSettings.setLayout(new java.awt.GridLayout(1, 0));

        btnHelp.setBackground(new java.awt.Color(255, 255, 255));
        btnHelp.setBorder(null);
        btnHelp.setMaximumSize(new java.awt.Dimension(20, 20));
        btnHelp.setMinimumSize(new java.awt.Dimension(20, 20));
        btnHelp.setPreferredSize(new java.awt.Dimension(20, 20));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanelSettings.add(btnHelp);

        btnInfo.setBackground(new java.awt.Color(255, 255, 255));
        btnInfo.setBorder(null);
        btnInfo.setMaximumSize(new java.awt.Dimension(20, 20));
        btnInfo.setMinimumSize(new java.awt.Dimension(20, 20));
        btnInfo.setPreferredSize(new java.awt.Dimension(20, 20));
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jPanelSettings.add(btnInfo);

        btnContact.setBackground(new java.awt.Color(255, 255, 255));
        btnContact.setBorder(null);
        btnContact.setMaximumSize(new java.awt.Dimension(30, 30));
        btnContact.setMinimumSize(new java.awt.Dimension(30, 30));
        btnContact.setPreferredSize(new java.awt.Dimension(30, 30));
        btnContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactActionPerformed(evt);
            }
        });
        jPanelSettings.add(btnContact);

        cmdClear.setBackground(new java.awt.Color(255, 255, 255));
        cmdClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmdClear.setBorder(null);
        cmdClear.setBorderPainted(false);
        cmdClear.setMaximumSize(new java.awt.Dimension(30, 30));
        cmdClear.setMinimumSize(new java.awt.Dimension(30, 30));
        cmdClear.setPreferredSize(new java.awt.Dimension(30, 30));
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });
        jPanelSettings.add(cmdClear);

        jPanel.add(jPanelSettings);

        jPanel7.setMaximumSize(new java.awt.Dimension(251, 20));
        jPanel7.setPreferredSize(new java.awt.Dimension(251, 20));
        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        lblAttendanceCardTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblAttendanceCardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendanceCardTitle.setText("Attendance Card");
        lblAttendanceCardTitle.setMaximumSize(new java.awt.Dimension(251, 20));
        lblAttendanceCardTitle.setMinimumSize(new java.awt.Dimension(251, 20));
        lblAttendanceCardTitle.setPreferredSize(new java.awt.Dimension(251, 20));
        jPanel7.add(lblAttendanceCardTitle);

        jPanel.add(jPanel7);

        getContentPane().add(jPanel);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(-1, 10, 10, 10));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(null);
        jPanel1.setOpaque(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 0, 2));

        lblEmpID1.setBackground(new java.awt.Color(255, 255, 255));
        lblEmpID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpID1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpID1.setText("ID #:");
        lblEmpID1.setToolTipText("");
        jPanel1.add(lblEmpID1);

        lblEmpID.setBackground(new java.awt.Color(255, 255, 255));
        lblEmpID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEmpID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpID.setToolTipText("");
        jPanel1.add(lblEmpID);

        lblEmpName1.setBackground(new java.awt.Color(255, 255, 255));
        lblEmpName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpName1.setText("Name:");
        lblEmpName1.setToolTipText("");
        jPanel1.add(lblEmpName1);

        lblEmpName.setBackground(new java.awt.Color(255, 255, 255));
        lblEmpName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEmpName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpName.setToolTipText("");
        jPanel1.add(lblEmpName);

        lblDivision1.setBackground(new java.awt.Color(255, 255, 255));
        lblDivision1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDivision1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDivision1.setText("Position:");
        lblDivision1.setToolTipText("");
        jPanel1.add(lblDivision1);

        lblDivision.setBackground(new java.awt.Color(255, 255, 255));
        lblDivision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDivision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDivision.setToolTipText("");
        jPanel1.add(lblDivision);

        lblSection1.setBackground(new java.awt.Color(255, 255, 255));
        lblSection1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSection1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSection1.setText("Department:");
        lblSection1.setToolTipText("");
        jPanel1.add(lblSection1);

        lblSection.setBackground(new java.awt.Color(255, 255, 255));
        lblSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSection.setToolTipText("");
        jPanel1.add(lblSection);

        jPanel4.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Morning (AM)");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel2);

        lblAMin1.setBackground(new java.awt.Color(255, 255, 255));
        lblAMin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAMin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAMin1.setText("Time In:");
        lblAMin1.setToolTipText("");
        lblAMin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblAMin1);

        lblAMin.setBackground(new java.awt.Color(255, 255, 255));
        lblAMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAMin.setToolTipText("");
        lblAMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblAMin);

        lblAMout1.setBackground(new java.awt.Color(255, 255, 255));
        lblAMout1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAMout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAMout1.setText("Time Out:");
        lblAMout1.setToolTipText("");
        lblAMout1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblAMout1);

        lblAMout.setBackground(new java.awt.Color(255, 255, 255));
        lblAMout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAMout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAMout.setToolTipText("");
        lblAMout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblAMout);

        jPanel4.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Afternoon (PM)");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel9);

        lblPMin1.setBackground(new java.awt.Color(255, 255, 255));
        lblPMin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPMin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMin1.setText("Time In (PM)  :");
        lblPMin1.setToolTipText("");
        lblPMin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPMin1);

        lblPMin.setBackground(new java.awt.Color(255, 255, 255));
        lblPMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMin.setToolTipText("");
        lblPMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPMin);

        lblPMout1.setBackground(new java.awt.Color(255, 255, 255));
        lblPMout1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPMout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMout1.setText("Time Out (PM):");
        lblPMout1.setToolTipText("");
        lblPMout1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPMout1);

        lblPMout.setBackground(new java.awt.Color(255, 255, 255));
        lblPMout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPMout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMout.setToolTipText("");
        lblPMout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPMout);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4);

        setLocation(new java.awt.Point(0, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void cmdTimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimeInActionPerformed
        // TODO add your handling code here:
        setGreen();
    }//GEN-LAST:event_cmdTimeInActionPerformed

    private void cmdTimeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimeOutActionPerformed
        // TODO add your handling code here:
        setRed(); 
    }//GEN-LAST:event_cmdTimeOutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //setCalendar();
       // lblTitle.setText("Mariano Marcos Memorial Hospital and Medical Center");
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        // TODO add your handling code here:
        lblEmpID.setText("");
        lblEmpName.setText("");
        lblDivision.setText("");
        lblSection.setText("");
        lblAMin.setText("");
        lblAMout.setText("");
        lblPMin.setText("");
        lblPMout.setText("");
        setCalendar();
    }//GEN-LAST:event_cmdClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //SettingsWindow ssss = new SettingsWindow();
        //ssss.show(true);
//        try {
//            if(dp.createIndex()) {
//                //Crud myCrud = new Crud();
//                //setAnnouncements(myCrud.getAnnouncements());
//                MainGUI.popUp("Machine Database updated successfully", "Information");
//            }
//            else
//            MainGUI.popUp("Operation encountered an Error!", "Error");
//        } catch(Exception e) {
//
//        }
        AttendanceMonitoring.end();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        showInstructions();
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        showInfo();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactActionPerformed
        // TODO add your handling code here:
//        try {
//                    // Check if Desktop is supported and browsing action is available
//                    if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
//                        Desktop.getDesktop().browse(new URI(Config.SERVER_URL)); // Open the URL in the default browser
//                    } else {
//                        System.out.println("Desktop browsing is not supported on this platform.");
//                    }
//                } catch (Exception ex) {
//                    ex.printStackTrace(); // Handle exceptions like invalid URI or IOExceptions
//                }
        isScanningAttendance=false;
        this.setVisible(false);
        this.dispose();
        dp.release();
        FpRegistration fpreg = new FpRegistration();
        fpreg.setVisible(true);
    }//GEN-LAST:event_btnContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //Look and feel
        
		try {UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}
		catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                while(isScanningAttendance) {new MainGUI().setVisible(true);}
                
            }
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnBanner;
    javax.swing.JButton btnContact;
    javax.swing.JButton btnHelp;
    javax.swing.JButton btnInfo;
    public static javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JButton cmdClear;
    javax.swing.JButton cmdTimeIn;
    javax.swing.JButton cmdTimeOut;
    javax.swing.JButton jButton1;
    private static javax.swing.JFrame jFrame1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel9;
    private static javax.swing.JOptionPane jOptionPane1;
    javax.swing.JPanel jPanel;
    static javax.swing.JPanel jPanel1;
    static javax.swing.JPanel jPanel2;
    static javax.swing.JPanel jPanel3;
    static javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    javax.swing.JPanel jPanelBanner;
    javax.swing.JPanel jPanelCompanyName;
    javax.swing.JPanel jPanelDateTimeDisplay;
    javax.swing.JPanel jPanelSettings;
    javax.swing.JPanel jPanelTimeInTimeOutButtons;
    public static javax.swing.JLabel lblAMin;
    public static javax.swing.JLabel lblAMin1;
    public static javax.swing.JLabel lblAMout;
    public static javax.swing.JLabel lblAMout1;
    static javax.swing.JLabel lblAttendanceCardTitle;
    static javax.swing.JLabel lblCompanyName;
    public static javax.swing.JLabel lblDay;
    public static javax.swing.JLabel lblDivision;
    public static javax.swing.JLabel lblDivision1;
    public static javax.swing.JLabel lblEmpID;
    public static javax.swing.JLabel lblEmpID1;
    public static javax.swing.JLabel lblEmpName;
    public static javax.swing.JLabel lblEmpName1;
    public static javax.swing.JLabel lblPMin;
    public static javax.swing.JLabel lblPMin1;
    public static javax.swing.JLabel lblPMout;
    public static javax.swing.JLabel lblPMout1;
    public static javax.swing.JLabel lblSection;
    public static javax.swing.JLabel lblSection1;
    javax.swing.JLabel lblSystemName;
    public static javax.swing.JLabel lblTime;
    javax.swing.JTextField txtP;
    // End of variables declaration//GEN-END:variables
    
    public static boolean infoBox(String infoMessage, String titleBar) throws UnsupportedAudioFileException, IOException, LineUnavailableException
    {   
      //lbl_prompt.setText(titleBar+": " +infoMessage+".");
      //VoiceManager vm = VoiceManager.getInstance(); 
      //Voice voice = vm.getVoice("kevin16");
      //voice.allocate();
      //voice.speak(titleBar+": " +infoMessage+".");
      //jOptionPane1.showMessageDialog(null, infoMessage, titleBar, jOptionPane1.INFORMATION_MESSAGE);
//      String bip = "";  
      if(titleBar.equalsIgnoreCase("Verified")) {
          
        jPanel2.setBackground(Color.GREEN);
        jPanel3.setBackground(Color.GREEN);
        jPanel4.setBackground(Color.GREEN);
        jPanel1.setBackground(Color.GREEN);
        playAudio(Config.AUDIO_SUCCESS);
        
      } else {
            jPanel2.setBackground(Color.RED);
            jPanel3.setBackground(Color.RED);
            jPanel4.setBackground(Color.RED);
            jPanel1.setBackground(Color.RED);
          
          playAudio(Config.AUDIO_ERROR);
      }
      lblAttendanceCardTitle.setText(infoMessage);
     
      return true;
      
    }
    
    public static void playAudio(String url) throws UnsupportedAudioFileException, LineUnavailableException, IOException {
        /*audio*/
        File audioFile = new File(url) ;
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(audioFile);
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    }
    
    public static void popUp(String infoMessage, String titleBar)
    {   
        jOptionPane1.showMessageDialog(null, infoMessage, titleBar, jOptionPane1.INFORMATION_MESSAGE);  
    }
     
    public static void setCalendar() {
        
                //tblCalendar.setModel(mtblCalendar);
                //Add headers
//		String[] headers = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"}; //All headers
//		for (int i=0; i<7; i++){
//			mtblCalendar.addColumn(headers[i]);
//		}
                
                //Single cell selection
//		tblCalendar.setColumnSelectionAllowed(true);
//		tblCalendar.setRowSelectionAllowed(true);
//		tblCalendar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//                //Set row/column count
//		tblCalendar.setRowHeight(35);
//		mtblCalendar.setColumnCount(7);
//		mtblCalendar.setRowCount(6);
//                tblCalendar = new JTable(mtblCalendar);
                //Get real month/year
		GregorianCalendar cal = new GregorianCalendar(); //Create calendar
		realDay = cal.get(GregorianCalendar.DAY_OF_MONTH); //Get day
                
		 realMonth = cal.get(GregorianCalendar.MONTH); //Get month
		 realYear = cal.get(GregorianCalendar.YEAR); //Get year
		// currentMonth = realMonth; //Match month and year
		// currentYear = realYear;
                //Refresh calendar
		 refreshCalendar (); //Refresh calendar
    }
    
    public static void refreshCalendar() {
                //Variables
		String[] months =  {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
                String[] weeks =  {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
		int som; //Number Of Days, Start Of Month
                
		//Get first day of month and number of days
		GregorianCalendar cal = new GregorianCalendar(realYear, realMonth, realDay);
		//nod = cal.getActualMaximum(GregorianCalendar.DAY_OF_MONTH);
		som = cal.get(GregorianCalendar.DAY_OF_WEEK);
		lblDay.setText(weeks[som-1]+", "+months[realMonth]+" "+realDay+", "+realYear);
		//Draw calendar
//		for (int i=1; i<=nod; i++){
//			int row = (i+som-2)/7;
//			int column  =  (i+som-2)%7;
//                        mtblCalendar.setValueAt(i, row, column);
//                }
                
                //tblCalendar.setModel(mtblCalendar);
                //tblCalendar = new JTable(mtblCalendar);  
                
		//Apply renderers
                //tblCalendar.setDefaultRenderer(tblCalendar.getColumnClass(0), new tblCalendarRenderer());
    }
//    
   /*static class tblCalendarRenderer extends DefaultTableCellRenderer{
                @Override
		public Component getTableCellRendererComponent (JTable table, Object value, boolean selected, boolean focused, int row, int column){
			super.getTableCellRendererComponent(table, value, selected, focused, row, column);
                        //JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, selected, focused, row, column);
                        //Component c = super.getTableCellRendererComponent(table, value, selected, focused, row, column);
                        if (column == 0 || column == 6){ //Week-end
				setBackground(new Color(255, 220, 220));
			}
			else{ //Week
				setBackground(new Color(255, 255, 255));
			}
			if (value != null){
				if (Integer.parseInt(value.toString()) == realDay && currentMonth == realMonth && currentYear == realYear){ //Today
					setBackground(new Color(220, 220, 255));
				}
			}
			setBorder(null);
			setForeground(Color.black);
			return this;  
		}
                
	} */

    public void setGreen() {
        cmdTimeIn.setBackground(Color.GREEN);
        cmdTimeOut.setBackground(Color.lightGray);
        timeType = 0;
    }
    
    public void setRed() {
        cmdTimeIn.setBackground(Color.lightGray);
        cmdTimeOut.setBackground(Color.RED);
        timeType = 1;
    }
    
//    public void congrats(String msg) {
//        //jLabel13.setBackground(new java.awt.Color(240, 234, 186));
//        //jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aa.gif"))); // NOI18N
//        //jLabel13.setVisible(true);
//        //jLabel14.setText("Congrats Doctora!");
//    
//        ImageIcon icon = new ImageIcon(getClass().getResource("/img/aa.gif")); // Replace with the path to your image file
//        JLabel label = new JLabel(icon);
//        
//       
//        JOptionPane.showMessageDialog(null, label, "Congratulations!", JOptionPane.PLAIN_MESSAGE);
//        popUp(msg,"Congratulations!");
//    }
    
    public void happyBirthday() {
        //jLabel13.setBackground(new java.awt.Color(240, 234, 186));
        //jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aa.gif"))); // NOI18N
        //jLabel13.setVisible(true);
        //jLabel14.setText("Congrats Doctora!");
    
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/birthday-happy-birthday.gif")); // Replace with the path to your image file
        JLabel label = new JLabel(icon);
        
       
        JOptionPane.showMessageDialog(null, label, "Happy Birthday!", JOptionPane.PLAIN_MESSAGE);
    }
    
    public static void resetUI() {
        jPanel2.setBackground(Color.WHITE);
        jPanel3.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
        jPanel1.setBackground(Color.WHITE);
        lblAttendanceCardTitle.setText("Attendance Card");
    }
    
    public static void showInstructions() {
        final String[] INSTRUCTIONS = {
            "Click 'Time In' or `Time Out` button",
            "Colors Green and Red are indicators that the button is selected.",
            "Scan finger on the fingerprint reader.",
            "If color Green flashes on the screen it means a successful process",
            "Review your digital attendance card.",
            "Click `X` button to close your digital attendance card.",
            "If color Red flashes on the screen it means a you should try again"
        };
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(INSTRUCTIONS.length,1));
        for(int i=0; i<INSTRUCTIONS.length; i++) {
            JLabel label = new JLabel();
            label.setText((i+1)+". "+INSTRUCTIONS[i]);
            panel.add(label);
        }
        
        JOptionPane.showMessageDialog(null, panel, "How to Time In/Time Out", JOptionPane.PLAIN_MESSAGE);
    }
    
    public static void showInfo() {
        final String[] INSTRUCTIONS = {
            "Company ID: "+Config.COMPANY_ID,
            "Machine ID: "+Config.MACHINE_ID,
            "Machine Location: "+Config.MACHINE_LOCATION,
            "Date: "+Config.DATE_SET,
            "Connected to: "+Config.DB_NAME,
            "DIR: "+System.getProperty("user.dir")
        };
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(INSTRUCTIONS.length,1));
        for(int i=0; i<INSTRUCTIONS.length; i++) {
            JLabel label = new JLabel();
            label.setText("* "+INSTRUCTIONS[i]);
            panel.add(label);
        }
        
        JOptionPane.showMessageDialog(null, panel, "Machine Info", JOptionPane.PLAIN_MESSAGE);
    }

//    public void setAnnouncements(HashMap<String, String> hashmap) {
//       
//        if(!hashmap.isEmpty()) {
//            keys = hashmap.keySet().toArray(new String[0]);
//            currentIndex = 0;
//            // Start the timer to change the label's text every 5 seconds
//            timer = new Timer(1000, e -> {
//                   String key = keys[currentIndex];
//                    String nextText = hashmap.get(key);
//                    lblAnnouncementTitle.setText(key);
//                    txtAnnouncmentContent.setText(nextText);
//                    currentIndex = (currentIndex + 1) % keys.length; 
//            });
//            timer.start();
//        } else {
//            lblAnnouncementTitle.setText("");
//            txtAnnouncmentContent.setText("");
//        }
//        
//    }
}
